language: cpp
sudo: required

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: "/pr\\/.*/"

env:
  global:
    # twine password.
    - secure: "TTYUO/dbT7fN2Dt3A9eaSI7/kvyySk6RGlh7LInnfswqdBkiPQKh593rR2wHXAqgY7f8CyHUjPoKiml3WLuK6n5jKyzE6zHaq8BjHYmlbSa82+BGUxcyQAI3eJrXCJDIVsV9EITUyWsyVYo0XRLnhOoIbiI9quClMmzBU6ZNWks="

matrix:
  include:
    - env: PYKEP_BUILD="DebugGCC"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-gold
    - env: PYKEP_BUILD="ReleaseGCC"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-gold
    - env: PYKEP_BUILD="CoverageGCC"
      dist: bionic
      compiler: gcc 
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packa1ges:
          - binutils-gold
    - env: PYKEP_BUILD="Python38"
      dist: bionic
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
  # Activate if matplotlib is available in py38 via the PyPi
  #- env: PYKEP_BUILD="manylinux64Py38" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
  #  sudo: required
  #  services:
  #  - docker
  - env: PYKEP_BUILD="manylinux64Py37" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: PYKEP_BUILD="manylinux64Py36" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    sudo: required
    services:
    - docker
install:
- docker pull $DOCKER_IMAGE
script:
- mkdir build
- cd build
# NOTE: currently, travis does not stop automatically if one of these
# 2 scripts returns an error code. Thus, we run them together as a single
# command, so that if install_deps.sh fails the whole build fails immediately
# rather than executing install_travis.sh as well. See
# https://github.com/travis-ci/travis-ci/issues/1066
- ../tools/install_deps.sh && ../tools/install_travis.sh
notifications:
  email: false
