language: cpp

compiler:
  - gcc
  - clang
  
script:
  - mkdir build && cd build
  - cmake ../ -DBUILD_PYKEP="ON"

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libboost-date-time-dev libboost-serialization-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi

branches:
  only:
    - master
 
os:
  - linux
  - osx

osx_image: xcode61
