language: cpp
sudo: required

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: "/pr\\/.*/"

env:
  global:
    # twine password.
    - secure: "TTYUO/dbT7fN2Dt3A9eaSI7/kvyySk6RGlh7LInnfswqdBkiPQKh593rR2wHXAqgY7f8CyHUjPoKiml3WLuK6n5jKyzE6zHaq8BjHYmlbSa82+BGUxcyQAI3eJrXCJDIVsV9EITUyWsyVYo0XRLnhOoIbiI9quClMmzBU6ZNWks="

matrix:
  include:
  - env: PYKEP_BUILD="manylinux64Py38" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    sudo: required
    services:
    - docker
  include:
  - env: PYKEP_BUILD="manylinux64Py67" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    sudo: required
    services:
    - docker
  - env: PYKEP_BUILD="manylinux64Py36" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    sudo: required
    services:
    - docker
install:
- docker pull $DOCKER_IMAGE
script:
- mkdir build
- cd build
- bash ../tools/install_travis.sh
notifications:
  email: false
  
