language: cpp
sudo: required
branches:
  except: "/pr\\/.*/"

env:
  global:
    secure: X39My22te29N1jN6wZ1mfR9Lgx82X5TGaWJSX6Yqp4KGkeg1PU6+C8SjFZmsZmmA26vJXsgT+WC909M043zp6Gkpx/CTzr9HZCwdImDMzWfTq6Q9h1Z44KsgSEi39XCiFd6/1hvxG+EHZTS5672y/3NoyU4TBaWstYwQFxbXcfQ=

matrix:
  include:
  - env: PYKEP_BUILD="manylinux64Py37" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: PYKEP_BUILD="manylinux64Py36" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: PYKEP_BUILD="manylinux64Py35" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  - env: PYKEP_BUILD="manylinux64Py27" DOCKER_IMAGE="quay.io/pypa/manylinux1_x86_64"
    sudo: required
    services:
    - docker
  
install:
- docker pull $DOCKER_IMAGE
script:
- mkdir build
- cd build
- bash ../tools/install_travis.sh
notifications:
  email: false


